# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: postgresql
  encoding: unicode
  database: heekari_development
  pool: 5
  template: template0

test:
  adapter: postgresql
  encoding: unicode
  database: heekari_test
  pool: 5
  template: template0

production:
  adapter: postgresql
  encoding: unicode
  database: heekari_production
  pool: 5
  template: template0
